name: "On Tag -> Deploy a release to pypi"

#TODO: in the future, try to do that : https://mestrak.com/blog/semantic-release-with-python-poetry-github-actions-20nn

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Patch Sources with "tag version ref"
        run: python .github/workflows/update_version.py ${{github.ref_name}}

      - name: Install dependencies # could be done by poetry ;-)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-asyncio
          python -m pip install uvicorn starlette tornado kivy pywebview fake-winreg

      - name: Test htag pytests
        run: |
          python3 -m pytest .

      - name: Create htag artifact from source versionned
        uses: actions/upload-artifact@v4
        with:
          name: htag_release_sources_${{github.ref_name}}
          path: |
            htag/*

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.12
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}

